name= input("enter your name:   ")
print("name is:",name)
print("type of name is:" ,type(name))
print("hashcode of name is:" , id(name))
print("////////////////////////////////////////////////////")
age = input("enter yor age:   ")
print("age is:",age)
print("type of age ", type(age))
print("hashcode of name is:" , id(age))